* Introduction

Boar aims to be the perfect way to make sure your most important
digital information, like pictures, movies and documents, are stored
safely.

  * Boar makes it possible for you to restore any or all of your files from any point in time.
  * Boar makes it easy to maintain verified backups of your data, including file history.
  * Boar imposes no limits on file or repository sizes.
  * Using boar is an effective way to prevent data loss due to human or machine error.

If you are familiar with vcs software such as Subversion, you might
think of boar as "version control for large binary files". But keep
reading, because there is more to it.

Boar stores snapshots of directory trees in a local or remote
repository and provides tools to ensure that your data is consistent
and complete. You can keep just some or all of your data checked out
for viewing and editing.

The repository has a simple layout to ensure that the data can easily
be extracted even if the original software should be unavailable. This
simplicity makes boar ideal for data that needs safe long-term
storage.

* Installation

We are working to modernize the distribution of boar. Installation
currently is as follows for this repo.

Clone the legacy version and make a symlink to the script on your
path:

#+begin_src bash
git clone git@github.com:salotz/boar.git --branch v0.0.0 --single-branch
ln -s boar/boar $HOME/.local/bin
#+end_src

You will need to install some dependencies as well though which I have
compiled in the ~requirements.in~ file:

#+begin_src bash
pip install -r boar/requirements.in
#+end_src

Then you can just run it:

#+begin_src bash
boar
#+end_src

* Documentation

See the [[./wiki][wiki]].


* Contact and contributions

There is a very inactive [[https://groups.google.com/forum/#!forum/boarvcs][Google Groups Forum]]. If you want to help
revitalize this project use the issues on github for now.
